// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: sodor/sodor.proto

package sodor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TS_INIT    TaskState = 0
	TaskState_TS_RUNNING TaskState = 1
	TaskState_TS_STOPPED TaskState = 2
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TS_INIT",
		1: "TS_RUNNING",
		2: "TS_STOPPED",
	}
	TaskState_value = map[string]int32{
		"TS_INIT":    0,
		"TS_RUNNING": 1,
		"TS_STOPPED": 2,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_sodor_sodor_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_sodor_sodor_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_sodor_sodor_proto_rawDescGZIP(), []int{0}
}

type SchedulerMode int32

const (
	SchedulerMode_SM_None    SchedulerMode = 0
	SchedulerMode_SM_Crontab SchedulerMode = 1
)

// Enum value maps for SchedulerMode.
var (
	SchedulerMode_name = map[int32]string{
		0: "SM_None",
		1: "SM_Crontab",
	}
	SchedulerMode_value = map[string]int32{
		"SM_None":    0,
		"SM_Crontab": 1,
	}
)

func (x SchedulerMode) Enum() *SchedulerMode {
	p := new(SchedulerMode)
	*p = x
	return p
}

func (x SchedulerMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulerMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sodor_sodor_proto_enumTypes[1].Descriptor()
}

func (SchedulerMode) Type() protoreflect.EnumType {
	return &file_sodor_sodor_proto_enumTypes[1]
}

func (x SchedulerMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulerMode.Descriptor instead.
func (SchedulerMode) EnumDescriptor() ([]byte, []int) {
	return file_sodor_sodor_proto_rawDescGZIP(), []int{1}
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sodor_sodor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_sodor_sodor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_sodor_sodor_proto_rawDescGZIP(), []int{0}
}

type SchedulerParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CtSpec string `protobuf:"bytes,1,opt,name=ct_spec,json=ctSpec,proto3" json:"ct_spec,omitempty"`
}

func (x *SchedulerParam) Reset() {
	*x = SchedulerParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sodor_sodor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedulerParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerParam) ProtoMessage() {}

func (x *SchedulerParam) ProtoReflect() protoreflect.Message {
	mi := &file_sodor_sodor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerParam.ProtoReflect.Descriptor instead.
func (*SchedulerParam) Descriptor() ([]byte, []int) {
	return file_sodor_sodor_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulerParam) GetCtSpec() string {
	if x != nil {
		return x.CtSpec
	}
	return ""
}

type SchedulerOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode  SchedulerMode   `protobuf:"varint,1,opt,name=mode,proto3,enum=SchedulerMode" json:"mode,omitempty"`
	Param *SchedulerParam `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
}

func (x *SchedulerOption) Reset() {
	*x = SchedulerOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sodor_sodor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedulerOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerOption) ProtoMessage() {}

func (x *SchedulerOption) ProtoReflect() protoreflect.Message {
	mi := &file_sodor_sodor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerOption.ProtoReflect.Descriptor instead.
func (*SchedulerOption) Descriptor() ([]byte, []int) {
	return file_sodor_sodor_proto_rawDescGZIP(), []int{2}
}

func (x *SchedulerOption) GetMode() SchedulerMode {
	if x != nil {
		return x.Mode
	}
	return SchedulerMode_SM_None
}

func (x *SchedulerOption) GetParam() *SchedulerParam {
	if x != nil {
		return x.Param
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Script string           `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Host   string           `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Option *SchedulerOption `protobuf:"bytes,4,opt,name=option,proto3" json:"option,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sodor_sodor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_sodor_sodor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_sodor_sodor_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *Task) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Task) GetOption() *SchedulerOption {
	if x != nil {
		return x.Option
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tasks []*Task `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sodor_sodor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_sodor_sodor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_sodor_sodor_proto_rawDescGZIP(), []int{4}
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_sodor_sodor_proto protoreflect.FileDescriptor

var file_sodor_sodor_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x6f, 0x64, 0x6f, 0x72, 0x2f, 0x73, 0x6f, 0x64, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x0a, 0x0e,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x74, 0x53, 0x70, 0x65, 0x63, 0x22, 0x5c, 0x0a, 0x0f, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x25,
	0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x70, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x28, 0x0a,
	0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2a,
	0x38, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x54, 0x53, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x53, 0x5f,
	0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x53, 0x5f,
	0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x2c, 0x0a, 0x0d, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x4d,
	0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4d, 0x5f, 0x43, 0x72,
	0x6f, 0x6e, 0x74, 0x61, 0x62, 0x10, 0x01, 0x32, 0x2c, 0x0a, 0x0d, 0x46, 0x61, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x04, 0x2e, 0x4a, 0x6f, 0x62, 0x1a, 0x06, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x61, 0x62, 0x79, 0x53, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x6f, 0x64, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sodor_sodor_proto_rawDescOnce sync.Once
	file_sodor_sodor_proto_rawDescData = file_sodor_sodor_proto_rawDesc
)

func file_sodor_sodor_proto_rawDescGZIP() []byte {
	file_sodor_sodor_proto_rawDescOnce.Do(func() {
		file_sodor_sodor_proto_rawDescData = protoimpl.X.CompressGZIP(file_sodor_sodor_proto_rawDescData)
	})
	return file_sodor_sodor_proto_rawDescData
}

var file_sodor_sodor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sodor_sodor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sodor_sodor_proto_goTypes = []interface{}{
	(TaskState)(0),          // 0: TaskState
	(SchedulerMode)(0),      // 1: SchedulerMode
	(*Reply)(nil),           // 2: Reply
	(*SchedulerParam)(nil),  // 3: SchedulerParam
	(*SchedulerOption)(nil), // 4: SchedulerOption
	(*Task)(nil),            // 5: Task
	(*Job)(nil),             // 6: Job
}
var file_sodor_sodor_proto_depIdxs = []int32{
	1, // 0: SchedulerOption.mode:type_name -> SchedulerMode
	3, // 1: SchedulerOption.param:type_name -> SchedulerParam
	4, // 2: Task.option:type_name -> SchedulerOption
	5, // 3: Job.tasks:type_name -> Task
	6, // 4: FatController.CreateJob:input_type -> Job
	2, // 5: FatController.CreateJob:output_type -> Reply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sodor_sodor_proto_init() }
func file_sodor_sodor_proto_init() {
	if File_sodor_sodor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sodor_sodor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sodor_sodor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedulerParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sodor_sodor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedulerOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sodor_sodor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sodor_sodor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sodor_sodor_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sodor_sodor_proto_goTypes,
		DependencyIndexes: file_sodor_sodor_proto_depIdxs,
		EnumInfos:         file_sodor_sodor_proto_enumTypes,
		MessageInfos:      file_sodor_sodor_proto_msgTypes,
	}.Build()
	File_sodor_sodor_proto = out.File
	file_sodor_sodor_proto_rawDesc = nil
	file_sodor_sodor_proto_goTypes = nil
	file_sodor_sodor_proto_depIdxs = nil
}
